# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable_9',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
                ('Dep_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_9',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep1_25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('s_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP1_25',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep1_prof_25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP1_PROF_25',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep1_stud_24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP1_STUD_24',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep2_24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('s_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP2_24',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep2_prof_25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP2_PROF_25',
            },
        ),
        migrations.CreateModel(
            name='Timetable_dep2_stud_24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('Subject_name', models.CharField(max_length=30)),
                ('Day', models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thurday', 'Thurday')], max_length=30)),
                ('Time_slot_no', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CMS_TIMETABLE_DEP2_STUD_24',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_dep', models.IntegerField(default=1)),
                ('user_type', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CMS_USER',
            },
        ),
    ]
